### ISSUE TITLE
Version 5 causes build conflicts due to build files being shipped

### ISSUE THREAD

**Issue by brettcannon** [dusty-phillips/rescript-zora#13]
Looking at https://www.npmjs.com/package/@dusty-phillips/rescript-zora?activeTab=code it seems things such as `.merlin` and `lib/bs` got shipped due to the `.npmignore` file existing and being blank. That causes build failures because the compiler used might not align with what the user of the library has, e.g. https://github.com/brettcannon/check-for-changed-files/actions/runs/9210746204/job/25338461041?pr=99#step:5:503 .

And FYI, https://rescript-lang.org/docs/manual/latest/project-structure#publishing suggests not shipping the JS files when the library wraps an existing JS library (although maybe you included them for the blog post series?).

**Comment by brettcannon** [comment]
Unfortunately fixing this will require a new release (and maybe yanking the 5.0.0 release?).

**Comment by brettcannon** [comment]
I also opened https://forum.rescript-lang.org/t/what-would-belong-in-a-gitignore-template-for-rescript/5263 to find out exactly what should be ignored.

**Comment by brettcannon** [comment]
And in case you're wondering why this is happening, https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package suggests that having a `.npmignore` overrides your `.gitignore`. Probably another solution is to just copy the `.gitignore` over to `.npmignore` (or maybe symlink it?).

**Comment by dusty-phillips** [comment]
I'm pretty sure the library predates that publishing advice. Looking at the git history, I think `npx np` was complaining about the lack of a .npmignore and I just added it to shut it up without researching what it should contain.

**Comment by dusty-phillips** [comment]
Released 5.0.1 and unpublished 5.0.0. 🤞🏼
